### PR TITLE
Put team and advisors into collection and create separate careers page

### PR DESCRIPTION
**Pull request by antonleviathan**
People still need to fill out their details in the _people folder. There is a .md file for each person. For the picture, just add an image which is named "yourfirstname.ext" (for example anton.png). 

You will also need to uncomment the line called "photo:" in _people/yourname.md and add the name of your file next to it, for example:
photo: 'anton.png'

### CODE REVIEW

**Comment by antonleviathan** [comment]
@bertspaan Sorry I know I said I'd leave this alone but we wanted to get it done asap as the blog post written by Christian depends on this being completed. :(

**Comment by antonleviathan** [comment]
This is what it looks like btw:

scrn

**Comment by emideluxe** [comment]
@antonleviathan can you please revert my last commit 'add files via upload' b2075d8?

**Comment by FabrizioRomanoGenovese** [comment]
Obviously: Ask the relevant people if it is ok for us to put their faces on the website! I can take care of this if you want.

**Comment by antonleviathan** [comment]
@FabrizioRomanoGenovese, @wires feels he should be the one to talk to people personally about this (last I heard)

**Comment by FabrizioRomanoGenovese** [comment]
@antonleviathan fine for me. I'm just saying that we can't put any person's face on the website without explicit authorization, for obvious reasons. :)

**Comment by antonleviathan** [comment]
Duh?

**Comment by antonleviathan** [comment]
Closing this because the branch is outdated.

**Pull request closed without merging**
