### PR TITLE
halverwege alles

### PR DESCRIPTION
**Pull request by wires**

### CODE REVIEW

**Comment by wires** [comment]
this is a PR to test the netlify builds, see https://deploy-preview-33--nifty-ramanujan-39e3db.netlify.com/

**Comment by wires** [comment]
@bertspaan ^^

**Comment by antonleviathan** [comment]
Ok, added a few things. Let me know if we should do anything else before merging into master @jelle.

Also, I made a "VERY TYPE THEORY" graphic which we can sub in for "VERY BLOCKCHAIN" if you're into it.

**Comment by wires** [comment]
thanks! LGTM,

- didn't test the mailing list subscription, please make sure it works, it's the only really important thing on the page
- regarding the "very type theory", that's not good. please keep it very blockchain

**Comment by antonleviathan** [comment]
Ok roger that, the form works so I'm going to merge it. I moved the copy around slightly fyi.

**Comment by FabrizioRomanoGenovese** [comment]
Also because we don't have much type theory atm, not in the sense of type theory as mathematician think it at least xD

**Pull request merged**
